### ISSUE TITLE
Docker Image Status - Restarting

### ISSUE THREAD

**Issue by hasanals** [organization-x/omni#4]
Hi,

Thanks for the amazing tutorial, I'm currently trying to implement the omni template but whenever I try to build docker I keep getting **Restarting** as docker image status. I'm not sure what is wrong with the docker image or code inside that is causing it to repeatedly fail. I did all the steps in the video but still same error.

Also when I run the following code:
`
docker logs -f omni
`
I get the below error:
`Error: 'config.py' doesn't exist
Starting nginx: nginx.`

May you please let me know what might be causing the issue?

**Comment by neverabsolute** [comment]
Seems like an issue with file pathing, I am investigating now and will push a fix ASAP across all branches

**Comment by neverabsolute** [comment]
Ah figured out the issue, the Dockerfile doesn't copy the `config.py` file into the container.
